fix install kind argument invalid
kubesphere-sigs/ks pull request #193
Opened 2021-09-05 09:36 UTC by seanly

1. fix kind version argument invalid
2. fix ksVersion argument invalid

test result:
![image](https://user-images.githubusercontent.com/232069/132121244-ff5800f3-b019-4759-adfa-d73e5efa134d.png)

2021-09-06 06:16 UTC, LinuxSuRen reviewed
Thanks for helping fix some issues. But I didn't quite understand what the issues are. Can you just make them be clear?

2021-09-06 11:34 UTC, seanly commented
> Thanks for helping fix some issues. But I didn't quite understand what the issues are. Can you just make them be clear?

In the current version, the following use cases are exceptions

test case1: 
> execute command: 
bin/ks install kind --version=v1.19.7 --name=ks
expect:
kind version v1.19.7
actual:
kind version v1.18.2

test case2:
> execute command: 
bin/ks install kind --version=v1.19.7 --name=ks
expect: 
the image load uses kind cluster name is `ks`
actual:
the image load uses kind cluster name is `kind`

test case3:
> execute command: 
bin/ks install kind --version=v1.19.7 --name=ks
expect: 
ks-installer version is `v3.1.1`
actual:
Is still the image of the installed v3.0.0 without using the image specified by ksVersion

2021-09-06 12:07 UTC, LinuxSuRen requested changes

2021-09-06 12:07 UTC, LinuxSuRen commented on kubectl-plugin/install/kind.go
> +
why left an empty line here?

2021-09-06 12:07 UTC, LinuxSuRen commented on kubectl-plugin/install/kind.go
> +	kindConfigF := path.Join(os.TempDir(), "config.yaml")
I'd suggest deleting this temporary file after this command was done.

2021-09-06 12:07 UTC, LinuxSuRen commented on kubectl-plugin/install/kind.go
> +			err = commander.execCommand("kind", "load", "docker-image", "--name", kindName, image)
Please don't use `kindName` directly. You can add a new variable in line 187.

2021-09-06 13:50 UTC, seanly commented on kubectl-plugin/install/kind.go
> +
OK, I'll fix it.

2021-09-07 01:24 UTC, LinuxSuRen commented
hi @seanly , I don't recommend you force push the commits. I need to review all changed files because I cannot figure out what changes do you make in your last commit.

2021-09-07 01:26 UTC, LinuxSuRen reviewed
/lgtm

2021-09-07 01:40 UTC, seanly commented
> hi @seanly , I don't recommend you force push the commits. I need to review all changed files because I cannot figure out what changes do you make in your last commit.

2021-09-07 02:07 UTC, LinuxSuRen commented
>  I combined the two similar changes recently, Does not affect review already.

It's not true. The maintainer must review all changes. No one can guarantee for the changes.

2021-09-07 02:33 UTC, JohnNiang commented on kubectl-plugin/install/kind.go
> +		"kubesphere/jenkins-uc":     "v3.0.0",
IMO, some of them are deprecated and should not be used. Or we can determine the tags according to version of KubeSphere.

2021-09-07 02:42 UTC, JohnNiang commented on kubectl-plugin/install/kind.go
> +		"kubesphere/jenkins-uc":     "v3.0.0",
But the issue is unrelated with the PR. So this won't stop another maintainers from merging this though.

2021-09-07 02:49 UTC, merged